version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - |
        cd cicd
        npm i -g aws-cdk
        npm update
        pip install --upgrade pip
        python -m pip install -r requirements.txt